name: Docker - Ubuntu Impish
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: sakul6499-de
  IMAGE_NAME: cloudflare_ddns
  DOCKER_IMAGE: ubuntu
  DOCKER_IMAGE_VERSION: impish

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Docker Build
        run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_IMAGE }}-${{ env.DOCKER_IMAGE_VERSION }} --build-arg BASE_IMAGE=${{ env.DOCKER_IMAGE }} --build-arg BASE_IMAGE_VERSION=${{ env.DOCKER_IMAGE_VERSION }}

      - name: Docker Push
        if: ${{ github.event_name != 'pull_request' }}
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_IMAGE }}-${{ env.DOCKER_IMAGE_VERSION }}
